name: TorchDetectAML
channels:
  - pytorch
  - defaults
dependencies:
  - python=3.7
  - pytorch=1.1.0 
  - torchvision=0.3.0 
  - cudatoolkit=9.0
  - nb_conda=2.2.1
  - matplotlib=3.1.0
  - Cython=0.29.10
  - pip:
    - prompt_toolkit==2.0.9
    - azureml-sdk[notebooks, contrib]
    - papermill==1.1.0
    - python-dotenv==0.10.1
    - Pillow==6.1
    - numpy==1.17
    - azure-cli
